#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = purge ]; then
    ldconfig
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database -q /usr/share/applications
    fi
fi
